### ISSUE TITLE
[Bug]: [decimals] is an invalid option for [ble_monitor]

### ISSUE THREAD

**Issue by fesamper** [custom-components/ble_monitor#1176]
### What happened?

Hi,

Just having this issue after updating.
**Invalid config for [ble_monitor]: [decimals] is an invalid option for [ble_monitor]. Check: ble_monitor->ble_monitor->devices->0->decimals. (See /config/configuration.yaml, line 49).** 
```
ble_monitor:
  log_spikes: True
  discovery: False
  devices:
    # sensors
    - mac: 'XX:XX:XX:XX'
      name: 'temp_bano'
      encryption_key: 'XXXXXXXXXXXXXXXXXXXXXX'
      temperature_unit: C
      use_median: False
      decimals: 1
      restore_state: default
```
