### ISSUE TITLE
Changing configuration parameter to sensor level

### ISSUE THREAD

**Issue by Ernst79** [custom-components/ble_monitor#141]
Having an idea about the configuration parameters, that I would like to discuss. We now have configuration parameters as lists and dictionaries. In each list we have to define a MAC address, like this:

```
sensor:
  - platform: mitemp_bt
    encryptors:
      'A4:C1:38:2F:86:6C': '217C568CF5D22808DA20181502D84C1B'
    sensor_fahrenheit:
      - 'C4:7C:8D:6B:4F:F3'
    sensor_names:
      'A4:C1:38:2F:86:6C': 'Livingroom'
    whitelist:
     - 'B4:7C:8D:6B:4F:D3'
```

I think it would make more sense to define this per sensor, something like this.

```
sensor:
  - platform: mitemp_bt
     automatic_add: False
     entities:
     - mac: 'A4:C1:38:2F:86:6C'
       encryption_key: '217C568CF5D22808DA20181502D84C1B'
       name: 'Livingroom'
     - mac: 'C4:7C:8D:6B:4F:F3'
       unit_of_measurement: fahrenheit
     - mac: 'B4:7C:8D:6B:4F:D3' 
```

I understand that this is a significant breaking change, but it has the advantage that we can expand this in a second step to define other parameters on sensor level, like `rounding`, `median`, etc.

I’m not saying that we have to make this change, but I see some advantages, despite the breaking change (and quite some work to make this change). Let’s first discuss @Magalex2x14 what you think of this idea and see where we end up.

**Comment by Magalex2x14** [comment]
When I tested the changes with the whitelist today, I had the thought that something needs to be done with these dicts/lists, but I never got to the point of trying to formulate what exactly to do with them)

Looks great to me. We prepare lists for the parser only once at the start of the system, so the complication of this stage will not affect the overall performance of the component. Yes, this is a breaking update, but I think users will support it as the new format is much clearer.

The only thing is, instead of entities, I would write sensors (or devices?). And I also want to change automatic_add to something more sonorous ) If I understand correctly, this is a reference to whitelist: true. Something like autodiscovery, maybe )

In addition, if my memory serves me, there was a request from users to individually configure the averaging and rounding parameters for each device...

**Comment by Ernst79** [comment]
I will have a look tomorrow what the usual parameter naming is. I’ve seen sensors, as well as entities, I thought. I used automatic_add, as it was a parameter for rfxtrx component. autodiscovery sound better, I agree. I will check the developer docs of home assistant. 

For the rounding option, etc, we can make a parameter on component level, which can be overruled on sensor level (or perhaps even on temperature sensor/ humidity sensor level). 

Lets start with the dictionaries and lists first. I will start looking into this and will make a separate branch for this.

**Comment by Ernst79** [comment]
I did a study on the most common parameters in the code. 
- `device` (73x)
- `devices `(70x)
- `sensors `(44x)
- `entities `(20x)

and 
- `discovery `(18x, but some are doublures)
- `whitelist `(6x)
- `automatic_add `(12x, but 10 of them in rfxtrx)
- `discover `(1x)
- `auto_discovery `(0x)
- `autodiscovery `(0x)

I noticed that the following parameters are in homeassistant/const.py 
- `CONF_ENTITIES `= "entities"
- `CONF_DEVICE `= "device"
- `CONF_DEVICES `= "devices"
- `CONF_SENSORS `= "sensors"

- `CONF_DISCOVERY `= "discovery"
- `CONF_WHITELIST `= "whitelist"

I think, based on the above, I would choose `discovery` and `devices`. 

```
sensor:
  - platform: mitemp_bt
     discovery: False
     devices:
     - mac: 'A4:C1:38:2F:86:6C'
       encryption_key: '217C568CF5D22808DA20181502D84C1B'
       name: 'Livingroom'
     - mac: 'C4:7C:8D:6B:4F:F3'
       unit_of_measurement: fahrenheit
     - mac: 'B4:7C:8D:6B:4F:D3' 
```

What do you think?

**Comment by Magalex2x14** [comment]
Wow) Serious approach)
I like it, yes.

**Comment by Ernst79** [comment]
I've changed `unit_of_measurement `to `temperature_unit`. See [config validation](https://developers.home-assistant.io/docs/development_validation/)

```
sensor:
  - platform: mitemp_bt
     discovery: False
     devices:
     - mac: 'A4:C1:38:2F:86:6C'
       encryption_key: '217C568CF5D22808DA20181502D84C1B'
       name: 'Livingroom'
     - mac: 'C4:7C:8D:6B:4F:F3'
       temperature_unit: F
     - mac: 'B4:7C:8D:6B:4F:D3' 
```
