### ISSUE TITLE
LYWSD03MMC: not recognize after switching to ATC firmware

### ISSUE THREAD

**Issue by brenard** [custom-components/ble_monitor#182]
Hi,

I have 8 LYWSD03MMC devices connected to my Home Assistant and it's work great. To permit to control advertising interval, I try to switch one of these devices to [ATC firmware](https://github.com/atc1441/ATC_MiThermometer). No problem flashing, the device work great and I could configure it using [TelinkFlasher web interface](https://atc1441.github.io/TelinkFlasher.html).

On my Home Assistant configuration, I removed the _encryption_key_ option before restarting service. Since, this device is not recognized by Home Assistant, when all others work great. I try to remove it from the configuration and put it again, but it still not recognized.

There is something to be done so that the device is recognized again?

__My configuration :__

```
ble_monitor:
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  active_scan: False
  hci_interface: 0
  batt_entities: False
  discovery: True
  report_unknown: False
  restore_state: True
  devices:
    - mac: 'A4:C1:38:E3:3D:51' # 1
      name: 'Xiaomi Temp/hum Entrée'
      encryption_key: 'XXXXXXXXXXX'
      temperature_unit: C
[...]
    - mac: 'A4:C1:38:34:7D:82' # 6
      name: 'Xiaomi Temp/hum Chambre amis'
      temperature_unit: C
```

Thanks
