### ISSUE TITLE
LYWSD03MMC not recognized, faulty device?

### ISSUE THREAD

**Issue by ivanpavlina** [custom-components/ble_monitor#185]
Hi,

I bought two LYWSD03MMC sensors, flashed custom firmware through Telink Flasher and one is working great, i get temp/humidity/battery readings as expected but i have a problem with other one.

This is my config:
```
ble_monitor:
  batt_entities: True
  restore_state: True
  report_unknown: True
  devices:
  - mac: 'A4:C1:38:00:AE:2A'
    name: 'Hallway'
    temperature_unit: C
  - mac: 'A4:C1:38:E1:8C:8D'
    name: 'Livingroom'
    temperature_unit: C
```
Device with MAC A4:C1:38:00:AE:2A is working good, but A4:C1:38:E1:8C:8D is not getting any values in Hass. I turned on report_unknown, but still there aren't any messages about the 'unknown' device.

I downloaded app BLE Scanner on my phone and i see messages from both devices - 
This is raw data for mac A4:C1:38:00:AE:2A which is working fine:
`151695FE50305B05242AAE0038C1A40A10012A0000000B094154435F303041453241`

and this is raw data for faulty mac A4:C1:38:E1:8C:8D:
`10161A18A4C138E18C8D00FB21640C310B0B094154435F453138433844`

Message from faulty device is shorter, i looked through the code a bit and i see there should be bytes \x16\x95\xFE present in message but i dont see those in message from a faulty device.

I tried reflashing the custom firmware on the faulty device, shorting reset pins above the battery but nothing seems to help. Also i made sure that Advertising Type 'Mi Like' is set, that button was pressed about thousand times now while the device is connected to my phone :)

So, do I have a faulty device on my hand or is there some kind of remedy for this? Thank you in advance
