### ISSUE TITLE
No entities appearing in HA

### ISSUE THREAD

**Issue by Thibaud45** [custom-components/ble_monitor#212]
Hi, I try to integrate LYWSD03MMC sensors to my homeassistant. I followed the installation process without any problem.
I already connect the device to the Xiaomi Home app and I correctly receive the value.
I use a raspberry pi 4, my ble device is hci0 as expected, I don't have any problems scanning ble device with hcitool and gatttool
I configured the configuration.yaml file with this configuration:

```
ble_monitor:
  hci_interface: 0
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: False
  rounding: True
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'A4:C1:38:XX:XX:XX'
      name: 'test sensor ble monitor'
      encryption_key: '217C568CF5D22808DA20181502DXXXXX'
      temperature_unit: C
```

Once I reload homehassistant I can't find any entities appearing in the list, I was expecting to see it appearting to integrate is correctly.
I also tried with the "User Interface Configuration" but same result.

Am I doing something wrong or am I missing something to make it works ?

Thanks for your work and your help.

**Comment by Ernst79** [comment]
Hi, based on the above info, it's hard to tell what is wrong. Lets find out. 

A couple of question. 
- What list do you mean? 
- Can you check if the integration is displayed in the integration menu? 
- Does it display devices?

Please enable debug logging and post your logs, see the FAQ for instructions how to enable debug logging. 

And please use the insert code button if you submit your config or logs

**Comment by un1te** [comment]
![image](https://user-images.githubusercontent.com/32599945/102916350-1302e880-448c-11eb-8d0d-0acf3b34c57c.png)
integration displyed after i added  next in configuration.yaml

```
ble_monitor:
  hci_interface: 0
  discovery: false
  active_scan: False
  period: 60
  devices:
    - mac: '___'
      name: 'livingroom'
      encryption_key: ' ___'
      temperature_unit: C
```

**Comment by Ernst79** [comment]
Please enable debug logging and show your logs. Add the following to your configuration and restart HA.

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```
