### ISSUE TITLE
Device tracker “bluetooth_tracker“ stop working

### ISSUE THREAD

**Issue by Vovoronale** [custom-components/ble_monitor#23]
Device tracker “bluetooth_tracker“ stop working on raspberry pi 3+  when add platform mitemp_bt with error:
> Error looking up Bluetooth device
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/bluetooth/bluez.py", line 31, in discover_devices
>     lookup_class=lookup_class, device_id=device_id)
> _bluetooth.error: (4, 'Interrupted system call')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 140, in perform_bluetooth_update
>     devices = await hass.async_add_executor_job(discover_devices, device_id)
>   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/components/bluetooth_tracker/device_tracker.py", line 62, in discover_devices
>     device_id=device_id,
>   File "/usr/local/lib/python3.7/site-packages/bluetooth/bluez.py", line 34, in discover_devices
>     raise BluetoothError ("error communicating with local "
> bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter

System | HassOS 3.7
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.5
timezone | Europe/Kiev
version | 0.103.5
virtualenv | false

Configuration.yaml
```
sensor:
  - platform: mitemp_bt
device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true
```
