### ISSUE TITLE
Force request battery Mi Flora

### ISSUE THREAD

**Issue by amaciasf** [custom-components/ble_monitor#239]
Hi all!

First of all, thank you for creating this component. I love it, it's a great job.

I am a user of several Mi Flora v.3.2.4. This version does not report the battery.

Would it be possible to launch a non-passive request, every X hours to obtain this information?

I don't want to use the official "miflora" component because it does not link the battery with the device created by the passive component.

Thank you very much, greetings!

**Comment by Lemonadel** [comment]
It can be tricky, but I agree it would be nice to get this using BLE Passive. Currently as well as you I use official + this ble passive. Works flawlessly with 20 mi flora ( out of box HA mi flora had problems with 14+ mi floras).

I suppose that Battery state is simply not propagated via passive BLE messages and that might be a reason.

I use such config:
@ config.yaml 
```
  - platform: miflora
    mac: 'C4:7C:8D:xx:xx:xx'
    name: MiFlora3
    force_update: true
    median: 3
    go_unavailable_timeout: 43200
    scan_interval: 900
    monitored_conditions:
     - battery
```
and in plants.yaml

I merge it like (to use in ui-lovelace.yaml):
```
paloma:
  sensors:
    moisture: sensor.ble_moisture_c47c8dxxxxxx
    battery: sensor.MiFlora3_battery
    temperature: sensor.ble_temperature_ c47c8dxxxxxx
    conductivity: sensor.ble_conductivity_ c47c8dxxxxxx
    brightness: sensor.ble_illuminance_ c47c8dxxxxxx

```
