### ISSUE TITLE
Multiple devices warning

### ISSUE THREAD

**Issue by azlux** [custom-components/ble_monitor#328]
Hello,
I'm quite new on home assistant. I've make the ble monitor work, thank for that, it's a really great tool.
I've have a small issue, maybe not related to this project.
Here is my config related to my two thermometers:
```
ble_monitor:
  bt_interface: 'B8:**:**:**:**:4D'
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: True
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'A4:C1:**:**:**:9D'
      name: 'Living'
      encryption_key: '3EC442FC4***************C20010E3'
      temperature_unit: C
      decimals: 1
      use_median: False
      restore_state: default
  devices:
    - mac: 'A4:C1:**:**:**:21'
      name: 'bedroom'
      encryption_key: 'CCA34******************7ADCA052C33'
      temperature_unit: C
      decimals: 1
      use_median: False
      restore_state: default
```

I have a beatufull warning on my logs : `2021-04-17 01:12:28 WARNING (SyncWorker_1) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "devices". Check lines 14 and 22`
It's because I have `devices` twice.  But if I write the configuration like the following, the Living device isn't working anymore (report as NaN) : 
```
ble_monitor:
  bt_interface: 'B8:**:**:**:**:4D'
  [.....]
  restore_state: False
  devices:
    - mac: 'A4:C1:**:**:**:9D'
      name: 'Living'
      [.....]
    - mac: 'A4:C1:**:**:**:21'
      name: 'bedroom'
      [.....]
```

Any idea ?

Thank,
Az

**Comment by Ernst79** [comment]
Are you sure you didn't make a mistake. This should be OK. 

```
ble_monitor:
  bt_interface: 'B8:**:**:**:**:4D'
  discovery: True
  active_scan: False
  report_unknown: False
  batt_entities: True
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    - mac: 'A4:C1:**:**:**:9D'
      name: 'Living'
      encryption_key: '3EC442FC4***************C20010E3'
      temperature_unit: C
      decimals: 1
      use_median: False
      restore_state: default
    - mac: 'A4:C1:**:**:**:21'
      name: 'bedroom'
      encryption_key: 'CCA34******************7ADCA052C33'
      temperature_unit: C
      decimals: 1
      use_median: False
      restore_state: default
```
