### ISSUE TITLE
YM-K1501EU

### ISSUE THREAD

**Issue by KMDobrev** [custom-components/ble_monitor#332]
Hello, I have added Xiaomi brand kettle Home Assistant. I can see its general status, but I cannot turn it on or off. I added "**binary_sensor.ble_switch**" as a button but it doesn't work. Where am I making a mistake?

My yaml file

```
ble_monitor:
  discovery: True
  active_scan: False
  report_unknown: False
  period: 60
  log_spikes: False
  devices:
    - mac: 'AC:9A:22:F4:XX:XX'
      name: 'Keetle'
      temperature_unit: C
      decimals: 1
      use_median: False
      restore_state: default
```

![444](https://user-images.githubusercontent.com/77675496/115971960-f961d280-a54b-11eb-839b-6fd8d6f3e649.png)
![RR](https://user-images.githubusercontent.com/77675496/115972009-43e34f00-a54c-11eb-9207-b1f957963084.png)
