### ISSUE TITLE
feature request: temperature/humidity offset

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#341]
if you have time...

it could be useful to have the possibility to set and offset for all devices or a single one

thanks

**Comment by Ernst79** [comment]
It’s a bit complicated to add this to the ble_monitor code, as each device can have different sensor types. It would require a setting in the option menu for each type of sensor.

You can use a template sensor for adding an offset. 

```
sensor:
  - platform: template
    sensors:
      sun_state:
        friendly_name: "Humidity adjusted"
        unit_of_measurement: "%"
        value_template: >-
          {{ states.sensor.ble_humidity_livingroom.state | float + 2 }}
```
