### ISSUE TITLE
HomeAssistant Bluetooth via ESXi VMWare - how to?

### ISSUE THREAD

**Issue by sanderlv** [custom-components/ble_monitor#342]
Hello, trying to passthrough the bluetooth from my NUC8i5 to my homeassistant (hassos) and use it for BLE.

I have passed through multiple USB devices succesfully. But I have no luck so far with bluetooth. I get:

Homeassistant says:
```
 - name: 2-2.3
    sysfs: '/sys/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.3'
    dev_path: /dev/bus/usb/002/006
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '002'
      DEVNAME: /dev/bus/usb/002/006
      DEVNUM: '006'
      DEVPATH: '/devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.3'
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_MODEL: 0aaa
      ID_MODEL_ENC: 0aaa
      ID_MODEL_ID: 0aaa
      ID_PATH: 'pci-0000:02:00.0-usb-0:2.3'
      ID_PATH_TAG: pci-0000_02_00_0-usb-0_2_3
      ID_REVISION: '0002'
      ID_SERIAL: 8087_0aaa
      ID_USB_INTERFACES: ':e00101:'
      ID_VENDOR: '8087'
      ID_VENDOR_ENC: '8087'
      ID_VENDOR_ID: '8087'
      MAJOR: '189'
      MINOR: '133'
      PRODUCT: 8087/aaa/2
      SUBSYSTEM: usb
      TYPE: 224/1/1
      USEC_INITIALIZED: '4517296'
```

the integration says:
![image](https://user-images.githubusercontent.com/16528916/117268701-e0b0c100-ae57-11eb-83bf-4ba429ff7d92.png)
