### ISSUE TITLE
Mi Scale V1 outputs old value after HA restart

### ISSUE THREAD

**Issue by Kaibob2** [custom-components/ble_monitor#366]
There is a little problem with the output of the integration which is, i think, related to the `restore_state` somewhere here https://github.com/custom-components/ble_monitor/issues/292#issuecomment-820149472

When HA is restarted the integration outputs three values when i step on the scale. One as soon as the scale "connects" and then two afterwards after measuring is finished (display stops blinking). The first is the old value which was "saved" for the restore_state. The following two values are the correct ones which are shown on the scale display. 
From this moment on the integration outputs only two values as soon as the scale display stops blinking after i step on it. This works perfect until HA is rebooted.

As a sidenote: One value is send when the display stops blinking and resend when i step off the scale. Could one of them be omitted on integration level? The "step off" value is useless and i have to drop it manually every time.

**Comment by Ernst79** [comment]
I'm not sure I'm entirely understanding the problem. The Miscale V1 has two sensors, a "Weight" sensor and a "Non-stabilized weight" sensor, and one binary_sensor "weight removed". Which one are you talking about?

What do you mean with "output". The output of which sensor? The value should be updated right after the restart, not "when you step on the scale". Are you sure you have enabled the option `restore_state` in the options. The behavior you describe seems to correspond with `restore_state` being disabled?

About your sidenote, which sensor are you asking this for?

**Comment by Kaibob2** [comment]
I expected this will be hard to explain, this is why i postponed this issue quite long :)

I will try a different approach:
**Situation 1**
- HA is freshly restarted
- Scale is off for around 2 hours
- We are looking at the `sensor.ble_weight` sensor (not non stabilized, not weight removed)
- I step on the scale
- Sensor gets updated immediately with the value it had before HA was restarted. Let's say 80kg
- The digits on the scale start blinking
- The digits stop blinking and the sensor gets updated with the actual weight. Let's say 82kg
- I step off the scale
- The sensor gets updated again with the current weight (82kg)

Restart was at 09:08:43
Weighting was at 9:10:17

![after restart](https://user-images.githubusercontent.com/20832276/119802819-2dc80600-bedf-11eb-9e03-421713ec2305.jpg)


**Situation 2**
- HA is **NOT** freshly restarted
- Scale is off for around 2 hours
- We are looking at the `sensor.ble_weight` sensor (not non stabilized, not weight removed)
- I step on the scale
- The digits on the scale start blinking
- The digits stop blinking and the sensor gets updated with the actual weight. Let's say 82kg
- I step off the scale
- The sensor gets updated again with the current weight (82kg)

![running](https://user-images.githubusercontent.com/20832276/119802876-3ae4f500-bedf-11eb-899c-7967f3266096.jpg)

Please ignore the weights in the images. The "old" value and the "new" value is the same as i didn't gain or loose weight while testing today. In real life i weight myself every evening and if a restart occurs in the meantime the "old" value get's stored in a template sensor first and my automation reacts on this "old" value. As it's the same as yesterday Alexa says "You weight 80kg. No difference to yesterday" which is incorrect. In the above example I would expect her to say "You weight 82kg. 2kg heavier than yesterday"

Config:
```
discovery: True
#hci_interface: 0
batt_entities: True
bt_interface: "00:1A:7D:DA:71:03" #external Dongle
#bt_interface: "94:E6:F7:18:AD:20" #internal
report_unknown: False
restore_state: True
devices:
  - mac: "A4:C1:38:F2:DB:E9"
    name: "Wohnzimmer"
  - mac: "A4:C1:38:1A:6D:AB"
    name: "Badezimmer"
  - mac: "A4:C1:38:5A:A9:FA"
    name: "Kueche"
  - mac: "A4:C1:38:A7:68:25"
    name: "Werkstatt"
  - mac: "28:D1:27:24:11:5E"
    name: "Bewegungsmelder"
    encryption_key: "22da599a7e75df1e7413f0394f256733"
    reset_timer: 5
  - mac: "C8:47:8C:C0:95:89"
    name: "Waage"
```
