### ISSUE TITLE
Decryption MiBeacon V2/V3 advertisement failed: No encryption key found

### ISSUE THREAD

**Issue by perseus177** [custom-components/ble_monitor#383]
**Version** 

Version HA | core-2021.5.5
-- | --
**Passive BLE monitor integration**  |2.6.3
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.9
Operating System Family | Linux
Operating System Version | 5.10.17-v7l+
CPU Architecture | armv7l
Timezone | Europe/Prague

**Devices** 
3 X LYWSDCGQ
1 X YM-K1501
RPI4

**YAML Configuration** 

```
# Bluetooth Senzory
ble_monitor:
     active_scan: False
     batt_entities: True
     decimals: 2
     devices:
      - mac: 'MAC Address'
      - mac: 'MAC Address'
      - mac: 'MAC Address'
##################################### Kanvica      
      - mac: 'MAC Address'
```

**Error in Log** 

```

This error originated from a custom integration.

Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:644
Integration: Passive BLE monitor (documentation, issues)
First occurred: 30. mája 2021, 20:59:08 (2 occurrences)
Last logged: 31. mája 2021, 23:44:43

Decryption MiBeacon V2/V3 advertisement failed: No encryption key found
```
