### ISSUE TITLE
Strange issue regarding "No encryption key found" (LYWSD03MMC + pvvx 3.2)

### ISSUE THREAD

**Issue by Trunkenstein** [custom-components/ble_monitor#400]
Hello,

I've got a strange problem after flashing 5 x LYWSD03MMC with the latest pvvx firmware and then trying to configure them in HASS.

4 of the 5 devices work flawlessly, but the last one has a problem as I'm not able to decrypt the data because of a missing key.
I've already poked around the logs and the python files but I can't find any obvious problem.

My settings are:
configure.yaml
```
ble_monitor:
      discovery: False
      devices:
        - mac: 'A4:C1:38:XX:XX:XX'
          name: 'XX_HT1'
          encryption_key: '44036c04b1969...'
        - mac: 'A4:C1:38:YY:YY:YY'
          name: 'YY_HT2'
          encryption_key: 'THE_PROBLEMATIC_ONE'
        - mac: 'A4:C1:38:XX:XX:XX'
          name: 'XX_HT3'
          encryption_key: 'e2af2410738556...'
        - mac: 'A4:C1:38:XX:XX:XX'
          name: 'XX_HT4'
          encryption_key: 'e1d060bd1057a...'
        - mac: 'A4:C1:38:XX:XX:XX'
          name: 'XX_HT5'
          encryption_key: '0192837465564...'
```

The error message I'm getting is:

> 2021-06-10 18:35:55 ERROR (Thread-3) [custom_components.ble_monitor.ble_parser.atc] No encryption key found for ATC device with MAC: A4:C1:38:YY:YY:YY
> 2021-06-10 18:35:55 DEBUG (MainThread) [custom_components.ble_monitor.binary_sensor] Data binary sensor received: {'data': False, 'rssi': -86, 'mac': 'A4C138YYYYYY', 'type': 'ATC', 'packet': 31, 'firmware': 'ATC (Custom encrypted)'}
> 2021-06-10 18:35:55 DEBUG (MainThread) [custom_components.ble_monitor.sensor] Data measuring sensor received: {'data': False, 'rssi': -86, 'mac': 'A4C138YYYYYY', 'type': 'ATC', 'packet': 31, 'firmware': 'ATC (Custom encrypted)'}

The logs are telling me:

> 2021-06-10 18:34:35 DEBUG (MainThread) [custom_components.ble_monitor] 5 encryptors mac:key pairs loaded.

So, it seems that the ble_monitor is loading 5 mac:key pairs but it "looses" one when trying to decrypt the received packages.

Is there any debugging possibility to "print" the mac:key pairs and / or see where they get lost?

**Comment by Ernst79** [comment]
Yes, when you enable debug logging at debug level, you should see the keys that are loaded in the HA log. Add the following to configuration.yaml

```
logger:
  default: warn
  logs:
    custom_components.ble_monitor: debug
```

What you also can do is add a line in `ble_monitor/ble_parser/atc.py` (2nd line is added)

```python
def decrypt_atc(self, data, atc_mac):
    _LOGGER.debug("List of the encryption keys: %s", self.aeskeys)
    # try to find encryption key for current device
    try:
        key = self.aeskeys[atc_mac.lower()]
        if len(key) != 16:
            _LOGGER.error("Encryption key should be 16 bytes (32 characters) long")
    except KeyError:
        # no encryption key found
        _LOGGER.error("No encryption key found for ATC device with MAC: %s", to_mac(atc_mac))
        return None
    # prepare the data for decryption
    nonce = b"".join([atc_mac[::-1], data[:5]])
```
