### ISSUE TITLE
Cannot add Govee H5179 

### ISSUE THREAD

**Issue by JackTalisker** [custom-components/ble_monitor#448]
Today I tried to add my H5179 removing the former integration by Thrilleratplay (which was working flawlessly) and installing ble_monitor.
No success. I tried either the UI config or the yaml way.
The entities simply do not appear. No errors in HA log.
H5179 works well as reported by bluetoothctl scan.

**Comment by Ernst79** [comment]
Did you enable active_scan in the options?

**Comment by JackTalisker** [comment]
Of course I enabled it.

This is my yaml code:
```
ble_monitor:
  bt_interface: 'B8:27:EB:B1:6E:49'
  discovery: False
  active_scan: True
  report_unknown: False
  decimals: 1
  period: 60
  log_spikes: False
  use_median: False
  restore_state: False
  devices:
    # sensor
    - mac: 'E3:32:81:12:18:6F'
      name: 'Terrazza'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
```
Attached an hcidump taken during HA restart
[dump.txt](https://github.com/custom-components/ble_monitor/files/6872044/dump.txt)
