### ISSUE TITLE
Last successfully processed BLE message sensor

### ISSUE THREAD

**Issue by eValker** [custom-components/ble_monitor#520]
Hello guys,

I am highly appreciate this project and your great work :)

Unfortunately I am one of the users affected with the "RuntimeError: Event loop stopped before Future completed" error. I spent hours trying to figure out what is wrong with my setup, but nothing seems to fix it. I am struggling with this since HA update v2021.7. I've even switched from the hassio installation to the supervised on the RaspbianOS, but it didn't change anything. 

The solution I came up with is to just reset bluetooth controller (using _systemctl restart bluetooth_) and then everything is working fine for a while (about 4-5 hours, but sometimes it happens again after a few minutes).
The problem was when I should execute it. My first approach was to just parse HA's logs every few seconds and reset bluetooth once error phase appear. However, I've noticed that very often error is being thrown, but everything is still working fine (sensors are updated properly).
So I decided to start using "last_changed" attribute on the sensors. Once last changed bluetooth-based sensor is updated later than 30 second ago, I execute the restart script.  

Unfortunately, while reading changes-log of version 5.4.0, I noticed that it will no longer be an option. Opening sensors will be only updated after real state change and thus I won't be able to monitor whether integration still works or not. 

So here comes my question: Do you think it is possible for you to add new sensor that will store a time of last successful processing BLE message? This way me (and other users with the same problem) can tract this value and reset bluetooth controller when necessary.

I know this is a workaround to a real problem, but I really don't want to replace each bluetooth door sensor I have in my house :)

If you need more information regarding my setup in order to track core issue, please let me know. 
Base info:
* Device: Raspberry Pi 4B
* Installation type: Supervised on Raspbian GNU/Linux 10 (buster)
* BL dongle: ASUS USB-BT400 Bluetooth 4.0 USB Nano Class II
* Sensors:
  * XIAOMI MCCGQ02HL Door & Window Sensor 2 BlueTooth 5.1
  * XIAOMI mi temperature and humidity monitor 2 lywsd03mmc (with custom firmware)

**Comment by Ernst79** [comment]
You could monitor the temperature sensor in stead of the motion sensor, to keep an eye on the Bluetooth still working. You can also monitor the packet id, which is changed on each message, I think. Al far as I understand, last_changed  only looks at state changes, but attribute changes will still happen. 

I was thinking that it might be better to add you reset script directly in the code of BLE monitor, as you are not the only one with this nasty bug. Could you post your script?

**Comment by eValker** [comment]
Sorry for the delay, I haven't notice email notification about your reply :(

I am not sure whether my solution is suitable for default HassOS installation. I remember I had some issues with execution bluetooth restart service command. That was the reason why I switched to the supervised installation.
Anyway here it is. Maybe someone else can use it :)

First I created the template sensor:
```
name: "oldest_bt_temp_sensor_update"
state: >
{% set last_changed_min = [states.sensor.ble_temperature_temp_livingroom.last_changed, 
						   states.sensor.ble_temperature_temp_bedroom.last_changed, 
						   states.sensor.ble_temperature_temp_livingroom.last_changed] | min %}
{{ relative_time(last_changed_min) }}
attributes:
datetime: >
  {% set last_changed_min = [states.sensor.ble_temperature_temp_livingroom.last_changed, 
							 states.sensor.ble_temperature_temp_bedroom.last_changed, 
							 states.sensor.ble_temperature_temp_livingroom.last_changed] | min %}
  {{ last_changed_min }}
```
Then there is an automation that "restarts" bluetooth controller. I remember I had some issues with an execution of the restart command directly (probably because of the supervisor being inside a docker container). This is why I am doing it indirectly. If there is restart needed I am creating file on the disk and then cron job perform execution.

Automation:
```
---
alias: Reset bluetooth controller when error
trigger:
  - platform: time_pattern
    minutes: "/1"
condition:
  - condition: template
    value_template: >
      {{ (as_timestamp(now()) - as_timestamp(states.sensor.oldest_bt_temp_sensor_update.last_changed)) > 30 }}
  - condition: template # Throttle by not triggering push messages if triggered in the last 10 seconds
    value_template: >
      {{ not state_attr('automation.reset_bluetooth_controller_when_error','last_triggered') or (as_timestamp(now()) - as_timestamp(state_attr('automation.reset_bluetooth_controller_when_error','last_triggered'))) > 30 }}
action:
#  - service: persistent_notification.create
#    data:
#      title: BLE Scanner
#      message: BLE Scanner not working again!
  - service: shell_command.btt_reset
```

Shell command:
```
shell_command:
  btt_reset: touch /share/.restart_bluetooth
```

Cron (executes every 30 seconds):
```
* * * * * /root/bluetooth_reset.sh >/dev/null 2>&1
* * * * * ( sleep 30 ; /root/bluetooth_reset.sh >/dev/null 2>&1 )
```
Restart script:
```
#!/bin/bash

FILE=/usr/share/hassio/share/.restart_bluetooth

if [ -f "$FILE" ]; then
   /bin/systemctl restart bluetooth
   /bin/rm $FILE
fi
```

As I said before I think it is only going to work for the supervised installation :)
