### ISSUE TITLE
New Device: Huawei Scale AH100/CH100

### ISSUE THREAD

**Issue by wieluk** [custom-components/ble_monitor#578]
Hey I am just curious if this would be possible I read a little about this scale but I could not really get a point to start.

[This issue on openscale is the most information I found yet.](https://github.com/oliexdev/openScale/issues/378) 

I made the log file with this config:

``` yaml
ble_monitor:
  discovery: False
  active_scan: False
  report_unknown: Other
  bt_auto_restart: False
  devices:
    - mac: 'AA:AA:AA:AA:AA:AA'
      name: 'Scale'
```

[AH100output.txt](https://github.com/custom-components/ble_monitor/files/7669454/AH100output.txt)

If you need any more Information I am glad to help. I think the data is encrypted.
