### ISSUE TITLE
Adding 2x new Brifit/Thermoplus sensors to existing 4 - BLE cannot find or manually add

### ISSUE THREAD

**Issue by mjchantler** [custom-components/ble_monitor#582]
I purchased 2x more Brifit/Thermoplus sensors to add to my existing 4, which work flawlessly in BLE Monitor. They are the same brand and model as the earlier 4, from the same supplier. iPhone app integration has worked without issue, showing me 6 devices. 

I cannot get BLEMon to find these new 2x, nor can I add them manually. After multiple restarts and refreshes, they're still not showing available in devices.

**Comment by Ernst79** [comment]
Try to use the report_unkown function to see if there are BLE advertisements from these sensors. First, try it with `report_unkown: Brifit` and with `report_unknown: Thermoplus`. Otherwise, Use `report_unknown: Other`

For instructions about how to get the data and how to set the `logger`:
https://custom-components.github.io/ble_monitor/faq#my-sensor-is-not-in-the-list-of-supported-ones-how-to-request-implementation

**Comment by mjchantler** [comment]
No joy using the report_unknown: function for Brifit, Thermoplus or Other sadly. I'm at a complete loss? I've uninstalled BLEMon, cleaned out orphan entities/sensors and reinstalled and it still only detects the original 4x units, so there must be a hardware difference but yet they still work just fine with the iOS app?

**Comment by Ernst79** [comment]
You could try to make a hci dump

**Comment by mjchantler** [comment]
Whereabouts and in which file do I manually define the sensors within the .yaml file or ble_monitor folder structure? Maybe I can manually add the mac addresses and see if that works?

**Comment by Ernst79** [comment]
```
ble_monitor:
  devices:
    # sensors
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'Livingroom'
      encryption_key: '217C568CF5D22808DA20181502D84C1B'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
    - mac: 'C4:3C:4D:6B:4F:F3'
      reset_timer: 35
    # device trackers
    - mac: 'D4:3C:2D:4A:3C:D5'
      track_device: True
      tracker_scan_interval: 20
      consider_home: 180
```
