### ISSUE TITLE
iNODE Energy Meter is missing configurable "constant" value

### ISSUE THREAD

**Issue by VaillantHassIo** [custom-components/ble_monitor#666]
Ok. I figure that the iNode Energy Meter cant be added straight to the dashboard due to missing “state_class”, so i create a template sensor and adjusted the “constant” value

```
template:
  - sensor:
      - name: "energy total"        
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing        
        state:  "{{ states('sensor.ble_energy_d0f0184412e1') | float | multiply(0.1) | round(1) }}"
```

It would be great, if the iNODE Energy Meter implementation would receive a state_class and also if constant can be configured as i will work out of the box without the need to use the developer tools to pre-configure
