### ISSUE TITLE
Sensors not working when MAC address characters written in lower case

### ISSUE THREAD

**Issue by theliquid** [custom-components/ble_monitor#734]
Hi,
I just discovered that my Xiaomi BLE sensors don't work, when I write the characters in the MAC address in the configuration.yaml file in lower case.
Since writing the MAC address in lower case is a common practice, this seems to be a bug.

**Comment by Ernst79** [comment]
Can confirm the bug. It’s also happening in the UI configuration. When I change the upper case MAC to a lower case MAC, It will create additional entities with _2 at the end in the unique ID (sensor name is lower case) but it won’t update these, it will keep on updating the old ones with the upper case names.

**Comment by Ernst79** [comment]
Hmm, if I add a new sensor with lower case MAC, is does seem to works OK. Looking further....

**Comment by Ernst79** [comment]
Now, I tried with YAML. 

```yaml
ble_monitor:
  hci_interface: 0
  bt_auto_restart: False
  active_scan: False
  discovery: False
  period: 60
  use_median: False
  decimals: 1
  log_spikes: False
  restore_state: False
  report_unknown: False
  devices:
    # sensor
    - mac: 'a4:c3:38:5d:18:b4'
      name: 'Livingroom'
      encryption_key: 'b9ea895fac7eea6d30532432a5123456'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
```

It's working fine. 

![image](https://user-images.githubusercontent.com/24375847/154859577-b726d505-5887-4770-bbd1-f9ff714a5ee0.png)

Could you show me your configuration?
