### ISSUE TITLE
Mi Motion Sensor 2 - problem with encryption key

### ISSUE THREAD

**Issue by perseus177** [custom-components/ble_monitor#766]
**Mi Motion Sensor 2 - problem with encryption key**

**Steps for reproduce:**
1. I added Mi Motion Sensor 2 to Xiaomi app.
2. I found token and MAC address via https://github.com/Maxmudjon/Get_MiHome_devices_token
3. I added it to the HA configuration file 
```
ble_monitor:
     active_scan: True
     discovery: True
     decimals: 2
     devices: 
      - mac: '54:EF:44:C1:13:5F'
        encryption_key: '422887e1d8e3fe71ad3d68e4'  
        reset_timer: 35
        name: 'Senzor Pohybu Spalna' 
```
5. I restart HA 

**Observed behavior**: Error  - Encryption key should be 16 bytes (32 characters) long

```
This error originated from a custom integration.
Logger: custom_components.ble_monitor.ble_parser.xiaomi
Source: custom_components/ble_monitor/ble_parser/xiaomi.py:819
Integration: Passive BLE monitor (documentation, issues)
First occurred: 13:03:08 (21 occurrences)
Last logged: 13:22:15
Encryption key should be 16 bytes (32 characters) long

```

## System Health

version | core-2021.12.10
-- | --
installation_type | Home Assistant Supervised
ble_monitor | 7.9.5
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v7l+
arch | armv7l
timezone | Europe/Prague

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4726
Installed Version | 1.19.3
Stage | running
Available Repositories | 1005
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.6
disk_total | 109.8 GB
disk_used | 10.2 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), MariaDB (2.4.0), Mosquitto broker (6.0.1), Samba share (9.5.1), TasmoAdmin (0.16.0), Nginx Proxy Manager (0.11.0), Zigbee2mqtt (1.24.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 5
views | 11
mode | yaml

</details>
