### ISSUE TITLE
[Bug]:  restore_state at device level it is not working

### ISSUE THREAD

**Issue by 50494554524F** [custom-components/ble_monitor#998]
### What happened?

```
  ble_monitor:
    bt_auto_restart: true
    discovery: false
    decimals: 2
    devices:
      - name: 'Xiaomi - Window Sensor - Test'            
        mac: 'MAC'
        encryption_key: 'KEY'
        restore_state: true
```
the state is not preserved after restart and it remain on unavailable until an event occour...

ble_monitor: 9.1.1

thanks

### Sensor type

Xiaomi Window Sensor 2
